# Module 1 - Python & Data Science Fundamentals

## Codomax Data Scientist Internship

### Objective

Build a strong foundation in Python programming and understand the fundamental concepts of Data Science required for later internship modules.

### Topics Covered

- Python environment setup
- Variables and data types
- Lists and tuples
- Dictionaries
- Conditional statements
- Loops
- Functions
- File handling
- NumPy basics
- Pandas basics
- Data Science fundamentals
- Real-world applications of Data Science

In [ ]:
# Verify the Python environment

import sys

print("Python version:")
print(sys.version)

## 1. Variables and Data Types

Variables are used to store data in Python. Python supports different data types such as integers, floats, strings, and boolean values.

In [ ]:
# Basic variables and data types

name = "Parth"
age = 21
percentage = 87.5
is_student = True

print("Name:", name)
print("Age:", age)
print("Percentage:", percentage)
print("Student:", is_student)

print("\nData Types:")
print("name:", type(name))
print("age:", type(age))
print("percentage:", type(percentage))
print("is_student:", type(is_student))

## 2. Lists and Tuples

Lists and tuples are used to store multiple values. Lists are mutable, while tuples are immutable.

In [ ]:
# Working with a list

marks = [78, 85, 92, 88, 76]

print("Marks:", marks)
print("First mark:", marks[0])
print("Total marks:", sum(marks))
print("Average marks:", sum(marks) / len(marks))

In [1]:
# Working with a tuple

subjects = ("Python", "Statistics", "Machine Learning", "SQL")

print("Subjects:", subjects)
print("First subject:", subjects[0])
print("Number of subjects:", len(subjects))

Subjects: ('Python', 'Statistics', 'Machine Learning', 'SQL')
First subject: Python
Number of subjects: 4

## 3. Dictionaries

A dictionary stores data as key-value pairs and is useful for representing structured information.

In [2]:
# Working with a dictionary

student = {
    "name": "Parth",
    "age": 21,
    "course": "AI & Data Science",
    "score": 87
}

print("Student details:")

for key, value in student.items():
    print(f"{key}: {value}")

Student details:
name: Parth
age: 21
course: AI & Data Science
score: 87

## 4. Conditional Statements

Conditional statements allow a program to make decisions based on conditions.

In [3]:
# Using if-elif-else

score = 87

if score >= 90:
    grade = "A+"
elif score >= 75:
    grade = "A"
elif score >= 60:
    grade = "B"
else:
    grade = "C"

print("Score:", score)
print("Grade:", grade)

Score: 87
Grade: A

## 5. Loops

Loops are used to repeatedly execute a block of code.

In [4]:
# For loop

print("For loop:")

for number in range(1, 6):
    print(number)

For loop:
1
2
3
4
5

In [5]:
# While loop

print("While loop:")

count = 1

while count <= 5:
    print(count)
    count += 1

While loop:
1
2
3
4
5

## 6. Functions

Functions are reusable blocks of code that perform a specific task.

In [6]:
# Creating and using a function

def calculate_average(values):
    """Calculate the average of numeric values."""

    if len(values) == 0:
        return 0

    return sum(values) / len(values)


numbers = [10, 20, 30, 40, 50]

print("Numbers:", numbers)
print("Average:", calculate_average(numbers))

Numbers: [10, 20, 30, 40, 50]
Average: 30.0

## 7. File Handling

File handling allows Python programs to create, write, read, and process files.

In [7]:
# Writing data to a text file

file_name = "student_data.txt"

with open(file_name, "w") as file:
    file.write("Name,Score\n")
    file.write("Parth,87\n")
    file.write("Rahul,82\n")
    file.write("Aman,91\n")

print("File created successfully.")

File created successfully.

In [8]:
# Reading data from the file

with open("student_data.txt", "r") as file:
    content = file.read()

print(content)

Name,Score
Parth,87
Rahul,82
Aman,91

## 8. NumPy Basics

NumPy is a Python library used for numerical computing and efficient array operations.

In [10]:
# Basic NumPy operations

import numpy as np

values = np.array([10, 20, 30, 40, 50])

print("Array:", values)
print("Mean:", np.mean(values))
print("Minimum:", np.min(values))
print("Maximum:", np.max(values))
print("Standard Deviation:", np.std(values))

Array: [10 20 30 40 50]
Mean: 30.0
Minimum: 10
Maximum: 50
Standard Deviation: 14.142135623730951

## 9. Pandas Basics

Pandas is widely used in Data Science for data manipulation, analysis, and working with tabular datasets.

In [11]:
# Create a simple DataFrame

import pandas as pd

data = {
    "Name": ["A", "B", "C", "D"],
    "Age": [20, 22, 21, 23],
    "Score": [78, 91, 85, 88]
}

df = pd.DataFrame(data)

df

  Name  Age  Score
0    A   20     78
1    B   22     91
2    C   21     85
3    D   23     88

In [12]:
# Basic Pandas analysis

print("First rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nAverage score:", df["Score"].mean())
print("Highest score:", df["Score"].max())

First rows:

  Name  Age  Score
0    A   20     78
1    B   22     91
2    C   21     85
3    D   23     88

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

Average score: 85.5
Highest score: 91

## 10. Data Science Fundamentals

Data Science is the process of extracting useful information and insights from data using programming, statistics, mathematics, visualization, and machine learning techniques.

### Typical Data Science Workflow

1. Define the problem
2. Collect data
3. Clean and prepare data
4. Explore the data
5. Analyze and visualize the data
6. Build a machine learning model when required
7. Evaluate the results
8. Communicate insights and recommendations

### Common Data Science Applications

- Recommendation systems
- Fraud detection
- Customer segmentation
- Sales forecasting
- Healthcare analytics
- Financial risk analysis
- Predictive maintenance

# Conclusion

This module established the fundamental Python and Data Science skills required for the later internship modules.

The work covered Python programming fundamentals, data structures, control flow, functions, file handling, NumPy, Pandas, and the basic Data Science workflow.

These foundations will be used in subsequent modules for data analysis, data visualization, machine learning, and the final Data Science project.