# Codomax Internship - Module 2
## Data Analysis with Python

### Objective
To explore, clean, and analyze a dataset using Python,
Pandas, and NumPy.

In [38]:
## 1. Import Libraries

In [40]:
import pandas as pd
import numpy as np

## 2. Import CSV Dataset

In [41]:
df = pd.read_csv('/content/student_performance.csv')

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [42]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [43]:
df.shape

(1000, 8)

In [44]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [46]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [47]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [48]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [49]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Observation

The dataset contains student information along with their Mathematics,
Reading, and Writing scores. The numerical columns can be analyzed
using Pandas and NumPy.

In [50]:
df.duplicated().sum()

np.int64(0)

In [52]:
df = df.drop_duplicates()

In [53]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [54]:
df[['math score', 'reading score', 'writing score']].min()

math score        0
reading score    17
writing score    10
dtype: int64

In [55]:
print("Mean Math Score:", np.mean(df['math score']))
print("Mean Reading Score:", np.mean(df['reading score']))
print("Mean Writing Score:", np.mean(df['writing score']))

Mean Math Score: 66.089
Mean Reading Score: 69.169
Mean Writing Score: 68.054

In [56]:
print("Median Math Score:", np.median(df['math score']))
print("Median Reading Score:", np.median(df['reading score']))
print("Median Writing Score:", np.median(df['writing score']))

Median Math Score: 66.0
Median Reading Score: 70.0
Median Writing Score: 69.0

In [57]:
print("Minimum Math Score:", np.min(df['math score']))
print("Maximum Math Score:", np.max(df['math score']))

print("Minimum Reading Score:", np.min(df['reading score']))
print("Maximum Reading Score:", np.max(df['reading score']))

print("Minimum Writing Score:", np.min(df['writing score']))
print("Maximum Writing Score:", np.max(df['writing score']))

Minimum Math Score: 0
Maximum Math Score: 100
Minimum Reading Score: 17
Maximum Reading Score: 100
Minimum Writing Score: 10
Maximum Writing Score: 100

In [58]:
print("Math Standard Deviation:", np.std(df['math score']))
print("Reading Standard Deviation:", np.std(df['reading score']))
print("Writing Standard Deviation:", np.std(df['writing score']))

Math Standard Deviation: 15.155496659628165
Reading Standard Deviation: 14.59289001534652
Writing Standard Deviation: 15.188057281956757

In [59]:
print(df['math score'].mean())
print(df['reading score'].mean())
print(df['writing score'].mean())

66.089
69.169
68.054

In [60]:
print("Highest Math Score:", df['math score'].max())
print("Highest Reading Score:", df['reading score'].max())
print("Highest Writing Score:", df['writing score'].max())

Highest Math Score: 100
Highest Reading Score: 100
Highest Writing Score: 100

In [61]:
print("Lowest Math Score:", df['math score'].min())
print("Lowest Reading Score:", df['reading score'].min())
print("Lowest Writing Score:", df['writing score'].min())

Lowest Math Score: 0
Lowest Reading Score: 17
Lowest Writing Score: 10

In [62]:
df[df['math score'] > 80].head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79

In [63]:
df.sort_values('math score', ascending=False).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86

In [64]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

### Missing Value Check

The dataset was checked for missing values using `isnull().sum()`.
No missing values were found, so no missing-value replacement was
required.

## 8. Conclusion

In this task, the student performance dataset was imported and
explored using Python and Pandas.

Basic data-cleaning checks were performed, including checking for
duplicate and missing values. NumPy was used to calculate basic
statistical measures such as mean, median, minimum, maximum, and
standard deviation.

The task provided practical experience in working with CSV datasets
and performing basic data analysis using Pandas and NumPy.